/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Paquete;

import Red.Red;
import Topologias.Anillo;
import Topologias.Tbus;
import Topologias.Testrella;
import Topologias.Thub;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author marti
 */
public class Jframe extends javax.swing.JFrame {

    //JComboBox combo = new JComboBox();
    static LinkedList<Tbus> bus = new LinkedList();
    static LinkedList<Thub> hub = new LinkedList();

    static LinkedList<Testrella> estrella = new LinkedList();
    static LinkedList<Anillo> anillo = new LinkedList();
    DefaultListModel modelo = new DefaultListModel();
    DefaultListModel modelo2 = new DefaultListModel();
    String nodoc, tipoc, tipocbus, tipodispobus;
    String nompabus;

    public Jframe() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Red Lan");
        this.setResizable(false);
        this.jList1.setModel(modelo);

    }

    public void MostrarBus() {
        for (Red r : bus) {
            modelo.addElement(r.toString());
        }
    }

    public void MostrarEstrella() {
        for (Testrella r : estrella) {
            modelo.addElement(r.toString());
        }
    }

    public void Limpiar() {
        this.jTextField1ControlA.setText("");
        this.jTextField2Estandares.setText("");
        this.jTextField3VelocidadT.setText("");
        this.jTextField4SoporteT1.setText("");
        this.jTextField3dispositivo.setText("");
        this.jComboBox1Topologias.setSelectedIndex(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1ControlA = new javax.swing.JTextField();
        jTextField2Estandares = new javax.swing.JTextField();
        jTextField3VelocidadT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1Topologias = new javax.swing.JComboBox<>();
        jButton1AgregarNodo = new javax.swing.JButton();
        jTextField4SoporteT1 = new javax.swing.JTextField();
        jTextField3dispositivo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1Toplistar = new javax.swing.JComboBox<>();
        jButton1Listar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1Limpiar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1listareliminar = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jComboBox1elimiar = new javax.swing.JComboBox<>();
        jButton1eliminareliminar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1Toplistarpaquete = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1nodoinicio = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1nodofinal = new javax.swing.JComboBox<>();
        jButton1EnviarPaquete = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField1byte = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField1mensaje = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CREAR RED");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dispositivo :");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Soporte  transmision :");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Control Acceso :");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Estandares:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Velocidad Transmision:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Topologia:");

        jComboBox1Topologias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Bus", "Estrella", "Hub", "Anillo" }));
        jComboBox1Topologias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1TopologiasMouseClicked(evt);
            }
        });
        jComboBox1Topologias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1TopologiasActionPerformed(evt);
            }
        });

        jButton1AgregarNodo.setText("Agregar");
        jButton1AgregarNodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1AgregarNodoMouseClicked(evt);
            }
        });
        jButton1AgregarNodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1AgregarNodoActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextField1ControlA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextField2Estandares, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextField3VelocidadT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jComboBox1Topologias, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1AgregarNodo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextField4SoporteT1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextField3dispositivo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(55, 55, 55))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)))
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3dispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2Estandares, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1Topologias, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3VelocidadT, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jButton1AgregarNodo))))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1ControlA, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4SoporteT1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4SoporteT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField1ControlA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2Estandares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jTextField3VelocidadT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField3dispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBox1Topologias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6))
                .addGap(55, 55, 55)
                .addComponent(jButton1AgregarNodo)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar", jPanel2);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("LISTAR  RED");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Topologia:");

        jComboBox1Toplistar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Bus", "Estrella", "Hub", "Anillo" }));
        jComboBox1Toplistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ToplistarActionPerformed(evt);
            }
        });

        jButton1Listar.setText("Listar");
        jButton1Listar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1ListarMouseClicked(evt);
            }
        });
        jButton1Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ListarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        jButton1Limpiar.setText("Limpiar");
        jButton1Limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1LimpiarMouseClicked(evt);
            }
        });
        jButton1Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1LimpiarActionPerformed(evt);
            }
        });

        jDesktopPane2.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jComboBox1Toplistar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jButton1Listar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jButton1Limpiar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel8))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 33, Short.MAX_VALUE))
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1Toplistar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButton1Listar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1Limpiar)
                .addGap(75, 75, 75))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addGap(37, 37, 37)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox1Toplistar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1Listar)
                    .addComponent(jButton1Limpiar))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );

        jTabbedPane1.addTab("Listar", jPanel3);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ELIMINAR  NODO");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Topologia:");

        jComboBox1listareliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Bus", "Estrella", "Hub", "Anillo" }));
        jComboBox1listareliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1listareliminarActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Nodo:");

        jComboBox1elimiar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccionar", " " }));
        jComboBox1elimiar.setToolTipText("");
        jComboBox1elimiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1elimiarActionPerformed(evt);
            }
        });

        jButton1eliminareliminar.setText("Eliminar");
        jButton1eliminareliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1eliminareliminarActionPerformed(evt);
            }
        });

        jDesktopPane4.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jComboBox1listareliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jComboBox1elimiar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jButton1eliminareliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane4Layout = new javax.swing.GroupLayout(jDesktopPane4);
        jDesktopPane4.setLayout(jDesktopPane4Layout);
        jDesktopPane4Layout.setHorizontalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane4Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel13))
                    .addGroup(jDesktopPane4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1elimiar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1listareliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jDesktopPane4Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jButton1eliminareliminar)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jDesktopPane4Layout.setVerticalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel13)
                .addGap(34, 34, 34)
                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jComboBox1listareliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jComboBox1elimiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jButton1eliminareliminar)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane4)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane4)
        );

        jTabbedPane1.addTab("Eliminar", jPanel1);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Topologia:");

        jComboBox1Toplistarpaquete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Bus", "Estrella", "Hub", "Anillo" }));
        jComboBox1Toplistarpaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ToplistarpaqueteActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nodo inicio:");

        jComboBox1nodoinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1nodoinicioActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nodo Final:");

        jComboBox1nodofinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1nodofinalActionPerformed(evt);
            }
        });

        jButton1EnviarPaquete.setText("Enviar");
        jButton1EnviarPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1EnviarPaqueteActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Byte:");

        jTextField1byte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1byteActionPerformed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Mensaje:");

        jTextField1mensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1mensajeActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("ENVIAR MENSAJE");

        jDesktopPane3.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jComboBox1Toplistarpaquete, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jComboBox1nodoinicio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jComboBox1nodofinal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jButton1EnviarPaquete, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jTextField1byte, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jTextField1mensaje, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jDesktopPane3Layout.createSequentialGroup()
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField1byte, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jDesktopPane3Layout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jComboBox1nodoinicio, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jDesktopPane3Layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jComboBox1Toplistarpaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1mensaje)
                                    .addComponent(jComboBox1nodofinal, 0, 117, Short.MAX_VALUE))
                                .addGap(4, 4, 4))))
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jButton1EnviarPaquete)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel18)
                .addGap(48, 48, 48)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1Toplistarpaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox1nodoinicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField1byte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBox1nodofinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jButton1EnviarPaquete)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane3)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane3)
        );

        jTabbedPane1.addTab("Enviar", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1mensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1mensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1mensajeActionPerformed

    private void jTextField1byteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1byteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1byteActionPerformed

    private void jButton1EnviarPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1EnviarPaqueteActionPerformed

        if (this.jComboBox1Toplistarpaquete.getSelectedIndex() == -1 || jComboBox1nodoinicio.getSelectedIndex() == -1
                || jTextField1byte.getText().equalsIgnoreCase("") || jTextField1mensaje.getText().equalsIgnoreCase("")
                || jComboBox1nodofinal.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Por favor verifica");
        } else {

            int i = this.jComboBox1Toplistarpaquete.getSelectedIndex();
            String nodoi = this.jComboBox1nodoinicio.getSelectedItem().toString();
            String nodof = this.jComboBox1nodofinal.getSelectedItem().toString();
            String mensaj = this.jTextField1mensaje.getText();
            int bt = Integer.parseInt(this.jTextField1byte.getText());
            Tbus aux = new Tbus();
            Testrella auxe = new Testrella();
            Thub auxhub = new Thub();
            Anillo auxan = new Anillo();
            if (i == 1) {
                //bus
                for (Tbus ob : bus) {

                    if (ob.getNomnbre().equalsIgnoreCase(nodof)) {
                        ob.setMensaje(mensaj);
                        ob.setBit(bt);
                        aux = ob;
                    } else {

                    }

                }
                JOptionPane.showMessageDialog(null, "Mensaje enviado al nodo " + aux.toString());
                limpiarPaquete();
            }
            if (i == 2) {
                for (Testrella ob : estrella) {
                    if (ob.getNombre().equalsIgnoreCase(nodof)) {
                        ob.setMensaje(mensaj);
                        ob.setBit(bt);
                        auxe = ob;
                    } else {

                    }

                }
                JOptionPane.showMessageDialog(null, "Mensaje enviado al nodo " + auxe.toString());
                limpiarPaquete();
            }
            if (i == 3) {

                // "hub";
                for (Thub ob : hub) {
                    if (ob.getNombre().equalsIgnoreCase(nodof)) {
                        ob.setMensaje(mensaj);
                        ob.setBit(bt);
                        auxhub = ob;
                    } else {

                    }

                }
                JOptionPane.showMessageDialog(null, "Mensaje enviado al nodo " + auxe.toString());
                limpiarPaquete();
            }
            if (i == 4) {

                // "anillo";
                for (Anillo ob : anillo) {
                    if (ob.getNombre().equalsIgnoreCase(nodof)) {
                        ob.setMensaje(mensaj);
                        ob.setBit(bt);
                        auxan = ob;
                    } else {

                    }

                }
                JOptionPane.showMessageDialog(null, "Mensaje enviado al nodo " + auxan.toString());

                limpiarPaquete();

            }
        }
    }//GEN-LAST:event_jButton1EnviarPaqueteActionPerformed

    private void jComboBox1nodofinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1nodofinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1nodofinalActionPerformed

    private void jComboBox1nodoinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1nodoinicioActionPerformed

    }//GEN-LAST:event_jComboBox1nodoinicioActionPerformed

    private void jComboBox1ToplistarpaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ToplistarpaqueteActionPerformed

        int i = this.jComboBox1Toplistarpaquete.getSelectedIndex();

        if (i == 1) {
            jComboBox1nodofinal.removeAllItems();
            jComboBox1nodoinicio.removeAllItems();
            for (Tbus ob : bus) {
                jComboBox1nodoinicio.addItem(ob.getNomnbre());
            }
            for (Tbus ob : bus) {
                jComboBox1nodofinal.addItem(ob.getNomnbre());
            }
        }
        if (i == 2) {
            jComboBox1nodofinal.removeAllItems();
            jComboBox1nodoinicio.removeAllItems();
            for (Testrella ob : estrella) {
                jComboBox1nodoinicio.addItem(ob.getNombre());
            }
            for (Testrella ob : estrella) {
                jComboBox1nodofinal.addItem(ob.getNombre());
            }

        }
        if (i == 3) {
            jComboBox1nodofinal.removeAllItems();
            // "hub";
            jComboBox1nodoinicio.removeAllItems();
            for (Thub ob : hub) {
                jComboBox1nodoinicio.addItem(ob.getNombre());
            }
            for (Thub ob : hub) {
                jComboBox1nodofinal.addItem(ob.getNombre());
            }
        }
        if (i == 4) {
            jComboBox1nodofinal.removeAllItems();
            // "anillo";
            jComboBox1nodoinicio.removeAllItems();
            for (Anillo ob : anillo) {
                jComboBox1nodoinicio.addItem(ob.getNombre());
            }
            for (Anillo ob : anillo) {
                jComboBox1nodofinal.addItem(ob.getNombre());
            }
        }
    }//GEN-LAST:event_jComboBox1ToplistarpaqueteActionPerformed

    private void jButton1eliminareliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1eliminareliminarActionPerformed
        //              int i = jComboBox1elimiar.getSelectedIndex();

        if (jComboBox1elimiar.getSelectedIndex() == -1 || jComboBox1listareliminar.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Por favor verifique");
        } else {
            int i = jComboBox1listareliminar.getSelectedIndex();
            if (i == 1) {
                String opc = jComboBox1elimiar.getSelectedItem().toString();
                for (Tbus ob : bus) {

                    if (ob.getNomnbre().equalsIgnoreCase(opc)) {
                        bus.remove(ob);
                        System.out.println("ob" + ob.toString());
                    } else {

                    }
                }

            }
            if (i == 2) {
                //estrella
                String opc = jComboBox1elimiar.getSelectedItem().toString();
                for (Testrella ob : estrella) {
                    if (ob.getNombre().equalsIgnoreCase(opc)) {
                        estrella.remove(ob);
                    } else {

                    }
                }

            }
            if (i == 3) {
                // "hub";
                String opc = jComboBox1elimiar.getSelectedItem().toString();
                for (Thub ob : hub) {
                    if (ob.getNombre().equalsIgnoreCase(opc)) {
                        hub.remove(ob);
                    } else {

                    }
                }
            }
            if (i == 4) {
                // "anillo";
                String opc = jComboBox1elimiar.getSelectedItem().toString();
                for (Anillo ob : anillo) {
                    if (ob.getNombre().equalsIgnoreCase(opc)) {
                        anillo.remove(ob);
                    } else {

                    }
                }
                //            }
            }
            JOptionPane.showMessageDialog(null, "Eliminado con exito");
            jComboBox1elimiar.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_jButton1eliminareliminarActionPerformed

    private void jComboBox1elimiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1elimiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1elimiarActionPerformed

    private void jComboBox1listareliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1listareliminarActionPerformed

        int i = jComboBox1listareliminar.getSelectedIndex();

        if (i == 1) {

            jComboBox1elimiar.removeAllItems();
            for (Tbus ob : bus) {
                jComboBox1elimiar.addItem(ob.getNomnbre());
            }

        }
        if (i == 2) {
            //estrella
            jComboBox1elimiar.removeAllItems();
            for (Testrella ob : estrella) {
                jComboBox1elimiar.addItem(ob.getNombre());
            }

        }
        if (i == 3) {
            // "hub";
            jComboBox1elimiar.removeAllItems();
            for (Thub ob : hub) {
                jComboBox1elimiar.addItem(ob.getNombre());
            }
        }
        if (i == 4) {
            // "anillo";
            jComboBox1elimiar.removeAllItems();
            for (Anillo ob : anillo) {
                jComboBox1elimiar.addItem(ob.getNombre());
            }
        }
    }//GEN-LAST:event_jComboBox1listareliminarActionPerformed

    private void jButton1LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1LimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1LimpiarActionPerformed

    private void jButton1LimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1LimpiarMouseClicked
        modelo.removeAllElements();
    }//GEN-LAST:event_jButton1LimpiarMouseClicked

    private void jButton1ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ListarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ListarActionPerformed

    private void jButton1ListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1ListarMouseClicked
        int i = this.jComboBox1Toplistar.getSelectedIndex();
        String opc = "";
        if (i == 0) {
            JOptionPane.showMessageDialog(null, "Por favor verifique");
        }
        if (i == 1) {
            opc = "bus";
            MostrarBus();

        }
        if (i == 2) {
            opc = "estrella";
            MostrarEstrella();
        }
        if (i == 3) {
            opc = "hub";
            for (Thub r : hub) {
                modelo.addElement(r.toString());
            }
            //
        }
        if (i == 4) {
            opc = "anillo";
            for (Anillo r : anillo) {
                modelo.addElement(r.toString());
            }

        }
    }//GEN-LAST:event_jButton1ListarMouseClicked

    private void jComboBox1ToplistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ToplistarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ToplistarActionPerformed

    private void jButton1AgregarNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1AgregarNodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1AgregarNodoActionPerformed

    private void jButton1AgregarNodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1AgregarNodoMouseClicked

        if (this.jTextField4SoporteT1.getText().equalsIgnoreCase("") || jTextField1ControlA.getText().equalsIgnoreCase("") || jTextField3VelocidadT.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Por favor rectifique");
        } else {

            String opc = "";
            String op = "";
            String s = jTextField4SoporteT1.getText();
            String con = this.jTextField1ControlA.getText();
            int v = Integer.parseInt(this.jTextField3VelocidadT.getText());
            String nom = this.jTextField3dispositivo.getText();
            int i = this.jComboBox1Topologias.getSelectedIndex();
            if (i == 1) {
                //"bus";
                Tbus ar = new Tbus(nom, tipocbus, tipodispobus, s, con, v);
                bus.add(ar);
                JOptionPane.showMessageDialog(null, "Agregado con exito");
                Limpiar();

            }
            if (i == 2) {
                opc = "estrella";
                Testrella es = new Testrella(nom, nodoc, tipoc, s, con, v);
                estrella.add(es);
                JOptionPane.showMessageDialog(null, "Agregado con exito");
                Limpiar();
            }
            if (i == 3) {
                opc = "hub";
                Thub h = new Thub(nom, s, con, v);
                hub.add(h);
                JOptionPane.showMessageDialog(null, "Agregado con exito");
                Limpiar();
            }
            if (i == 4) {
                opc = "anillo";
                Anillo ar = new Anillo(nom, s, con, v);
                anillo.add(ar);
                JOptionPane.showMessageDialog(null, "Agregado con exito");
                Limpiar();
            }

        }
    }//GEN-LAST:event_jButton1AgregarNodoMouseClicked

    private void jComboBox1TopologiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1TopologiasActionPerformed
        int i = this.jComboBox1Topologias.getSelectedIndex();
        String nom = this.jTextField3dispositivo.getText();

        if (i == 1) {
            tipocbus = JOptionPane.showInputDialog("Tipo de cableado");
            tipodispobus = JOptionPane.showInputDialog("Tipo de dispositivo final");
            nompabus = nom;

        }
        if (i == 2) {
            nodoc = JOptionPane.showInputDialog("Nodo principal");
            tipoc = JOptionPane.showInputDialog("Tipo de nodo ");

        }
        if (i == 3) {
            // "hub";
            //Thub h = new Thub(nom);
        }
        if (i == 4) {
            // "anillo";

        }
        //   llenarjpaquetes(nom);
    }//GEN-LAST:event_jComboBox1TopologiasActionPerformed

    private void jComboBox1TopologiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1TopologiasMouseClicked

    }//GEN-LAST:event_jComboBox1TopologiasMouseClicked

    public void limpiarPaquete() {
        jComboBox1Toplistarpaquete.setSelectedIndex(0);
        jComboBox1nodoinicio.setSelectedIndex(-1);
        jTextField1byte.setText("");
        jTextField1mensaje.setText("");
        jComboBox1nodofinal.setSelectedIndex(-1);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1AgregarNodo;
    private javax.swing.JButton jButton1EnviarPaquete;
    private javax.swing.JButton jButton1Limpiar;
    private javax.swing.JButton jButton1Listar;
    private javax.swing.JButton jButton1eliminareliminar;
    private javax.swing.JComboBox<String> jComboBox1Toplistar;
    private javax.swing.JComboBox<String> jComboBox1Toplistarpaquete;
    private javax.swing.JComboBox<String> jComboBox1Topologias;
    private javax.swing.JComboBox<String> jComboBox1elimiar;
    private javax.swing.JComboBox<String> jComboBox1listareliminar;
    private javax.swing.JComboBox<String> jComboBox1nodofinal;
    private javax.swing.JComboBox<String> jComboBox1nodoinicio;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1ControlA;
    private javax.swing.JTextField jTextField1byte;
    private javax.swing.JTextField jTextField1mensaje;
    private javax.swing.JTextField jTextField2Estandares;
    private javax.swing.JTextField jTextField3VelocidadT;
    private javax.swing.JTextField jTextField3dispositivo;
    private javax.swing.JTextField jTextField4SoporteT1;
    // End of variables declaration//GEN-END:variables
}
